import{Simulation,defaults,validateConfig,LEVEL_SECONDS}from'./simulator.js';

const $=s=>document.querySelector(s);const els={run:$('#run'),pause:$('#pause'),reset:$('#reset'),newSeed:$('#new-seed'),clock:$('#shared-clock'),speed:$('#playback-speed'),settings:$('#settings'),scrim:$('#scrim'),form:$('#settings-form'),error:$('#settings-error'),diff:$('#difference'),selected:$('#selected-agent')};
let configA={...defaults};let configB={...defaults,guardCount:2};let seed=20260920;let simA,simB,running=false,last=0,acc=0,selected=null;
const views={a:{field:$('#field-a'),chart:$('#chart-a'),metrics:$('#metrics-a'),status:$('#status-a'),summary:$('#summary-a')},b:{field:$('#field-b'),chart:$('#chart-b'),metrics:$('#metrics-b'),status:$('#status-b'),summary:$('#summary-b')}};

function reset(){simA=new Simulation(configA,seed);simB=new Simulation(configB,seed);running=false;last=0;acc=0;els.run.textContent='くらべる';els.pause.disabled=true;els.pause.textContent='一時停止';selected=null;els.selected.hidden=true;renderAll()}
function formatTime(t){const s=Math.floor(t);return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function summary(c){return`鬼${c.oniCount}（追跡${c.oniCount-c.guardCount-c.mochiCount}・守り${c.guardCount}・餅${c.mochiCount}）／逃げ${c.runnerCount}`}
const LABELS={oniCount:'鬼',runnerCount:'逃げ',guardCount:'守り',mochiCount:'餅',oniLevel:'鬼の速さ',runnerLevel:'逃げの速さ',fieldWidth:'横幅',fieldHeight:'奥行き',jailPosition:'牢屋の位置',jailWidth:'牢屋の幅',jailHeight:'牢屋の奥行き',captureTarget:'終了人数',timeLimit:'制限時間',protectionTime:'保護時間',rescueTendency:'助けやすさ',dangerDistance:'危険距離',guardRange:'守りの範囲',mochiLimit:'餅の上限',sprintDuration:'本気の時間',recoveryDuration:'回復歩き'};
function updateDiff(){const diffs=Object.keys(configA).filter(k=>configA[k]!==configB[k]);els.diff.textContent=diffs.length?`Bで変えた条件：${diffs.map(k=>`${LABELS[k]??k} ${display(configA[k])}→${display(configB[k])}`).join('、')}`:'AとBは同じ条件です。結果が同じになるか確かめられます。';views.a.summary.textContent=summary(configA);views.b.summary.textContent=summary(configB)}
function display(v){if(typeof v==='boolean')return v?'あり':'なし';const map={one:'1人',all:'全員',center:'中央',edge:'辺',corner:'隅'};return map[v]??v}
function resizeCanvas(canvas){const dpr=Math.min(devicePixelRatio||1,2);const r=canvas.getBoundingClientRect();const w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}return{w,h,dpr}}
function drawField(view,sim){const s=sim.snapshot(),{w,h,dpr}=resizeCanvas(view.field),ctx=view.field.getContext('2d');ctx.clearRect(0,0,w,h);const pad=12*dpr,fw=w-pad*2,fh=h-pad*2,sx=fw/s.config.fieldWidth,sy=fh/s.config.fieldHeight;ctx.fillStyle='#edf6e7';ctx.fillRect(pad,pad,fw,fh);ctx.strokeStyle='#6a7b61';ctx.lineWidth=1.5*dpr;ctx.strokeRect(pad,pad,fw,fh);
 const j=s.jail;ctx.fillStyle='rgba(107,95,80,.12)';ctx.fillRect(pad+j.x*sx,pad+j.y*sy,j.w*sx,j.h*sy);ctx.strokeStyle='#6b5f50';ctx.lineWidth=2*dpr;ctx.setLineDash([5*dpr,4*dpr]);ctx.strokeRect(pad+j.x*sx,pad+j.y*sy,j.w*sx,j.h*sy);ctx.setLineDash([]);ctx.fillStyle='#5b5146';ctx.font=`${11*dpr}px system-ui`;ctx.fillText('ろうや',pad+j.x*sx+5*dpr,pad+j.y*sy+14*dpr);
 if(s.config.symbolRescue){const cx=pad+j.cx*sx,cy=pad+j.cy*sy;ctx.save();ctx.translate(cx,cy);ctx.rotate(s.time*.7);ctx.fillStyle=s.symbol.cooldown>0?'#9ca3af':'#fbbf24';ctx.strokeStyle='#713f12';ctx.lineWidth=1.5*dpr;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?5*dpr:10*dpr;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();if(s.symbol.progress>0){ctx.fillStyle='#1d4ed8';ctx.fillRect(cx-12*dpr,cy+13*dpr,24*dpr*(s.symbol.progress/Math.max(.01,s.config.symbolHold)),3*dpr)}}
 for(const a of s.agents){const x=pad+a.x*sx,y=pad+a.y*sy,r=Math.max(4.5,Math.min(sx,sy)*.32)*dpr;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(a.team==='oni'){ctx.fillStyle=a.role==='guard'?'#0f766e':a.role==='mochi'?'#7c3aed':'#2563eb';ctx.fill();ctx.fillStyle='white';ctx.beginPath();ctx.arc(x,y,2*dpr,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle=a.state==='walkingToJail'?'#60a5fa':a.state==='jailed'?'#a8a29e':'#f97316';ctx.fill();ctx.strokeStyle=a.protectedUntil>s.time?'#16a34a':'white';ctx.lineWidth=a.protectedUntil>s.time?3*dpr:2*dpr;ctx.stroke()}if(a.moveMode==='本気で走る'){ctx.strokeStyle='#ef4444';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(x,y,r+2.5*dpr,0,Math.PI*2);ctx.stroke()}else if(a.moveMode==='回復中（歩く）'){ctx.strokeStyle='#64748b';ctx.setLineDash([2*dpr,2*dpr]);ctx.beginPath();ctx.arc(x,y,r+2.5*dpr,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}if(selected?.side===view.side&&selected.id===a.id){ctx.strokeStyle='#111827';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(x,y,r+5*dpr,0,Math.PI*2);ctx.stroke()}if(a.role==='guard'||a.role==='mochi'){ctx.fillStyle='white';ctx.font=`bold ${9*dpr}px system-ui`;ctx.textAlign='center';ctx.fillText(a.role==='guard'?'守':'餅',x,y+3*dpr)} }
 view.transform={pad,sx,sy,dpr};
}
function drawChart(view,sim){const s=sim.snapshot(),{w,h,dpr}=resizeCanvas(view.chart),ctx=view.chart.getContext('2d');ctx.clearRect(0,0,w,h);const p=8*dpr,max=Math.max(1,s.config.runnerCount);ctx.strokeStyle='#ddd8cc';ctx.beginPath();ctx.moveTo(p,h-p);ctx.lineTo(w-p,h-p);ctx.stroke();ctx.strokeStyle='#f97316';ctx.lineWidth=2*dpr;ctx.beginPath();s.history.forEach((v,i)=>{const x=p+(v.t/s.config.timeLimit)*(w-p*2),y=h-p-(v.n/max)*(h-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#637083';ctx.font=`${10*dpr}px system-ui`;ctx.fillText('つかまった人数',p,12*dpr)}
function renderMetrics(view,sim){const m=sim.metrics();view.metrics.innerHTML=[['つかまった',`${m.caught}人`],['平均待ち',`${m.avgWait.toFixed(1)}秒`],['最長待ち',`${m.maxWait.toFixed(1)}秒`],['救出',`${m.rescues}人`]].map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong></div>`).join('');view.status.textContent=sim.finished?sim.result:`${m.walking}人が牢屋へ歩き、${m.jailed}人が牢屋内、${m.rescues}人が救出`}
function updateSelected(){if(!selected)return;const sim=selected.side==='a'?simA:simB,best=sim.agents.find(a=>a.id===selected.id);if(!best)return;const state=best.team==='oni'?({chaser:'追跡',guard:'守り',mochi:'餅'}[best.role]):({active:best.action||'活動中',walkingToJail:'牢屋へ歩く',jailed:best.jailMode==='edge'?'境界近くで待つ':'牢屋内を移動'}[best.state]);$('#agent-state').textContent=`${state}／${best.moveMode}`}
function renderAll(){updateDiff();views.a.side='a';views.b.side='b';drawField(views.a,simA);drawField(views.b,simB);drawChart(views.a,simA);drawChart(views.b,simB);renderMetrics(views.a,simA);renderMetrics(views.b,simB);updateSelected();els.clock.textContent=formatTime(Math.max(simA.time,simB.time))}
function frame(ts){if(!running)return;if(!last)last=ts;acc+=Math.min(.1,(ts-last)/1000)*Number(els.speed.value);last=ts;let n=0;while(acc>=.05&&n<12){simA.step(.05);simB.step(.05);acc-=.05;n++}renderAll();if(simA.finished&&simB.finished){running=false;els.run.textContent='もう一度';els.pause.disabled=true;return}requestAnimationFrame(frame)}
function openSettings(){fillForm(configB);els.settings.hidden=false;els.scrim.hidden=false;$('#open-settings').setAttribute('aria-expanded','true');$('#close-settings').focus()}
function closeSettings(){els.settings.hidden=true;els.scrim.hidden=true;$('#open-settings').setAttribute('aria-expanded','false');$('#open-settings').focus()}
function fillForm(c){for(const [k,v]of Object.entries(c)){const el=els.form.elements[k];if(!el)continue;if(el.type==='checkbox')el.checked=v;else el.value=v}updateRangeOutputs();updateEquation()}
function readForm(){const c={...configB};for(const k of Object.keys(c)){const el=els.form.elements[k];if(!el)continue;if(el.type==='checkbox')c[k]=el.checked;else if(el.type==='number'||el.type==='range')c[k]=Number(el.value);else c[k]=el.value}return c}
function updateRangeOutputs(){els.form.querySelectorAll('output[data-for]').forEach(o=>{const n=o.dataset.for,v=Number(els.form.elements[n].value);o.textContent=n==='rescueTendency'?`${v}%`:`${v}（50m ${LEVEL_SECONDS[v-1]}秒相当）`})}
function updateEquation(){const c=readForm();$('#role-equation').textContent=`追跡する鬼 ${c.oniCount}−守り${c.guardCount}−餅${c.mochiCount}＝${c.oniCount-c.guardCount-c.mochiCount}人`}
function selectFromCanvas(side,e){const view=views[side],sim=side==='a'?simA:simB,t=view.transform,r=view.field.getBoundingClientRect(),x=(e.clientX-r.left)*(view.field.width/r.width),y=(e.clientY-r.top)*(view.field.height/r.height);let best=null,bd=Infinity;for(const a of sim.agents){const px=t.pad+a.x*t.sx,py=t.pad+a.y*t.sy,d=Math.hypot(x-px,y-py);if(d<bd){bd=d;best=a}}if(!best||bd>24*t.dpr)return;selected={side,id:best.id};els.selected.hidden=false;$('#agent-name').textContent=`${side.toUpperCase()}：${best.team==='oni'?'鬼':'逃げ'} ${best.id}`;$('#agent-state').textContent=best.team==='oni'?({chaser:'追跡',guard:'守り',mochi:'餅'}[best.role]):({active:best.action||'活動中',jailed:'牢屋で待機'}[best.state]);$('#agent-level').value=best.level;$('#agent-level-output').textContent=`${best.level}（50m ${LEVEL_SECONDS[best.level-1]}秒相当）`;renderAll()}

els.run.addEventListener('click',()=>{if(simA.finished&&simB.finished)reset();running=true;els.run.textContent='実験中';els.pause.disabled=false;last=0;requestAnimationFrame(frame)});els.pause.addEventListener('click',()=>{running=!running;els.pause.textContent=running?'一時停止':'再開';if(running){last=0;requestAnimationFrame(frame)}});els.reset.addEventListener('click',reset);els.newSeed.addEventListener('click',()=>{seed=(seed+7919)>>>0;reset()});$('#open-settings').addEventListener('click',openSettings);$('#close-settings').addEventListener('click',closeSettings);els.scrim.addEventListener('click',closeSettings);$('#copy-a').addEventListener('click',()=>fillForm(configA));els.form.addEventListener('input',()=>{updateRangeOutputs();updateEquation()});els.form.addEventListener('submit',e=>{e.preventDefault();const next=readForm(),errors=validateConfig(next);els.error.textContent=errors.join(' ');if(errors.length)return;configB=next;closeSettings();reset()});
for(const side of['a','b'])views[side].field.addEventListener('click',e=>selectFromCanvas(side,e));$('#agent-level').addEventListener('input',e=>{if(!selected)return;const sim=selected.side==='a'?simA:simB;sim.setAgentLevel(selected.id,e.target.value);$('#agent-level-output').textContent=`${e.target.value}（50m ${LEVEL_SECONDS[e.target.value-1]}秒相当）`;renderAll()});window.addEventListener('resize',renderAll);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!els.settings.hidden)closeSettings()});
reset();

