import{Simulation,defaults,validateConfig,LEVEL_SECONDS}from'./simulator.js';

const $=s=>document.querySelector(s);const els={run:$('#run'),pause:$('#pause'),reset:$('#reset'),newSeed:$('#new-seed'),clock:$('#shared-clock'),speed:$('#playback-speed'),layout:$('#comparison-layout'),openGlobal:$('#open-global-settings'),openA:$('#open-settings-a'),openB:$('#open-settings-b'),dualSettings:$('#dual-settings'),dualError:$('#dual-settings-error'),globalSettings:$('#global-settings'),globalForm:$('#global-settings-form'),globalTotal:$('#global-total'),globalTotalOutput:$('#global-total-output'),globalComparisonPreset:$('#global-comparison-preset'),globalComparisonPresetNote:$('#global-comparison-preset-note'),globalError:$('#global-settings-error'),settings:$('#settings'),sideLabel:$('#settings-side-label'),copyOther:$('#copy-other'),preset:$('#preset-select'),presetNote:$('#preset-note'),scrim:$('#scrim'),form:$('#settings-form'),error:$('#settings-error'),diff:$('#difference'),selected:$('#selected-agent')};
let configA={...defaults};let configB={...defaults,guardCount:2,rescuerPercent:30};let seed=20260920;let simA,simB,running=false,last=0,acc=0,selected=null,editingSide='b',editingTotal=defaults.oniCount+defaults.runnerCount,settingsTrigger=null,audioCtx=null;const eventCursors={a:0,b:0};
const PRESETS={standard:{...defaults,mochiCount:0},balanced:{...defaults,oniCount:4,runnerCount:20,guardCount:0,mochiCount:0,oniLevel:6,oniVariantPercent:25,oniVariantLevel:8,runnerLevel:6,runnerVariantPercent:30,runnerVariantLevel:7,evaderPercent:20,oniAvoiderPercent:20,rescuerPercent:5,captureTarget:18,timeLimit:120,rescueTendency:5},escape:{...defaults,oniCount:4,runnerCount:20,guardCount:1,mochiCount:0,oniVariantPercent:20,oniVariantLevel:6,runnerVariantPercent:40,runnerVariantLevel:8,evaderPercent:40,oniAvoiderPercent:20,rescuerPercent:10,captureTarget:20},pressure:{...defaults,oniCount:8,runnerCount:16,guardCount:1,mochiCount:0,oniVariantPercent:50,oniVariantLevel:8,runnerVariantPercent:20,runnerVariantLevel:6,evaderPercent:30,oniAvoiderPercent:30,rescuerPercent:10,captureTarget:16},equal:{...defaults,oniCount:12,runnerCount:12,guardCount:2,mochiCount:0,oniVariantPercent:30,oniVariantLevel:7,runnerVariantPercent:30,runnerVariantLevel:7,evaderPercent:20,oniAvoiderPercent:20,rescuerPercent:20,captureTarget:12},guard:{...defaults,guardCount:2,mochiCount:0,evaderPercent:20,oniAvoiderPercent:20,rescuerPercent:30}};
const PRESET_NOTES={standard:'試行開始点です。救出あり・70×40mでの検証仮説で、公式の最適値ではありません。',balanced:'100試合のモデル検証で鬼側47%、救出あり64%、救出中央値2回だった候補です。実際の児童の動きで再調整してください。',escape:'鬼が少なく、逃げと救出の動きが続きやすい条件です。',pressure:'鬼の圧力が高く、待ち時間や早期終了が増えるかを確かめます。',equal:'資料上の基本形です。救出ありでも遊びが続くかを確かめます。',guard:'人数比は1:3のまま、守りを1人から2人へ変える比較用です。',custom:'児童が立てた仮説に合わせて調整する条件です。'};
const COMPARISON_PRESETS={
 'standard-balanced':{a:'standard',b:'balanced',note:'従来の基準と、100試合で勝率・救出・待ち時間を調整した候補を比べます。'},
 'standard-escape':{a:'standard',b:'escape',note:'基本形と、鬼を減らして逃げ・救出が続きやすくした条件を比べます。'},
 'standard-pressure':{a:'standard',b:'pressure',note:'基本形と、鬼の人数・走力を強めた条件を比べます。'},
 'standard-guard':{a:'standard',b:'guard',note:'人数比を保ったまま、牢屋を守る鬼が1人と2人の場合を比べます。'},
 'escape-pressure':{a:'escape',b:'pressure',note:'逃げが動きやすい条件と、鬼の圧力が高い条件を比べます。'}
};
const views={a:{field:$('#field-a'),chart:$('#chart-a'),metrics:$('#metrics-a'),status:$('#status-a'),summary:$('#summary-a')},b:{field:$('#field-b'),chart:$('#chart-b'),metrics:$('#metrics-b'),status:$('#status-b'),summary:$('#summary-b')}};
const TYPE_LABELS={standard:'標準',evader:'逃げに徹する',oniAvoider:'鬼から離れる',rescuer:'助ける'};
const TYPE_FIELDS=['evaderPercent','oniAvoiderPercent','rescuerPercent'];
const GLOBAL_FIELDS=['fieldWidth','fieldHeight','timeLimit','sprintDuration','recoveryDuration','jailPosition','jailWidth','jailHeight','restrictedEnabled','restrictedMode','restrictedX','restrictedY','restrictedWidth','restrictedHeight'];
const dualStates={a:null,b:null};

function reset(){simA=new Simulation(configA,seed);simB=new Simulation(configB,seed);eventCursors.a=eventCursors.b=0;running=false;last=0;acc=0;els.run.textContent='くらべる';els.pause.disabled=true;els.pause.textContent='一時停止';selected=null;els.selected.hidden=true;renderAll()}
function formatTime(t){const s=Math.floor(t);return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function summary(c){return`鬼${c.oniCount}（追跡${c.oniCount-c.guardCount-c.mochiCount}・守り${c.guardCount}・餅${c.mochiCount}）／逃げ${c.runnerCount}／${c.fieldWidth}×${c.fieldHeight}m`}
const LABELS={oniCount:'鬼',runnerCount:'逃げ',guardCount:'守り',mochiCount:'餅',oniLevel:'鬼の速さ',oniVariantPercent:'別走力の鬼',oniVariantLevel:'別走力の鬼の速さ',runnerLevel:'逃げの速さ',runnerVariantPercent:'別走力の逃げ',runnerVariantLevel:'別走力の逃げの速さ',evaderPercent:'逃げに徹する',oniAvoiderPercent:'鬼から離れる',rescuerPercent:'助ける',fieldWidth:'横幅',fieldHeight:'奥行き',jailPosition:'牢屋の位置',jailWidth:'牢屋の幅',jailHeight:'牢屋の奥行き',restrictedEnabled:'立入禁止',restrictedMode:'禁止する側',restrictedX:'矩形の左端',restrictedY:'矩形の上端',restrictedWidth:'矩形の幅',restrictedHeight:'矩形の高さ',captureTarget:'終了人数',timeLimit:'制限時間',protectionTime:'保護時間',rescueTendency:'助けやすさ',dangerDistance:'危険距離',guardRange:'守りの範囲',retargetDistance:'標的を追う距離',nearbySwitchDistance:'近い逃げへの切替距離',mochiLimit:'餅の上限',sprintDuration:'本気の時間',recoveryDuration:'回復歩き'};
function updateDiff(){const diffs=Object.keys(configA).filter(k=>configA[k]!==configB[k]);els.diff.textContent=diffs.length?`Bで変えた条件：${diffs.map(k=>`${LABELS[k]??k} ${display(configA[k])}→${display(configB[k])}`).join('、')}`:'AとBは同じ条件です。結果が同じになるか確かめられます。';views.a.summary.textContent=summary(configA);views.b.summary.textContent=summary(configB)}
function display(v){if(typeof v==='boolean')return v?'あり':'なし';const map={one:'1人',all:'全員',center:'中央',right:'右上',edge:'辺',corner:'隅',inside:'内側',outside:'外側'};return map[v]??v}
function ensureAudio(){const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return null;if(!audioCtx)audioCtx=new AudioCtor();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function playCaptureSound(){const ctx=ensureAudio();if(!ctx)return;const now=ctx.currentTime,master=ctx.createGain();master.gain.setValueAtTime(.001,now);master.gain.exponentialRampToValueAtTime(.12,now+.008);master.gain.exponentialRampToValueAtTime(.001,now+.18);master.connect(ctx.destination);for(const [type,f0,f1,delay]of[['square',210,75,0],['sawtooth',520,120,.035]]){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(f0,now+delay);osc.frequency.exponentialRampToValueAtTime(f1,now+delay+.12);gain.gain.setValueAtTime(.45,now+delay);gain.gain.exponentialRampToValueAtTime(.01,now+delay+.13);osc.connect(gain).connect(master);osc.start(now+delay);osc.stop(now+delay+.14)}}
function playRescueSound(){const ctx=ensureAudio();if(!ctx)return;const now=ctx.currentTime;for(const [freq,volume]of[[880,.07],[1320,.035],[1760,.02]]){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,now);gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.001,now+.65);osc.connect(gain).connect(ctx.destination);osc.start(now);osc.stop(now+.68)}}
function playPendingSounds(){let capture=false,rescue=false;for(const [side,sim]of[['a',simA],['b',simB]]){while(eventCursors[side]<sim.events.length){const event=sim.events[eventCursors[side]++];if(event.type==='capture')capture=true;if(event.type==='rescue')rescue=true}}if(capture)playCaptureSound();if(rescue)playRescueSound()}
function resizeCanvas(canvas){const dpr=Math.min(devicePixelRatio||1,2);const r=canvas.getBoundingClientRect();const w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}return{w,h,dpr}}
function starPath(ctx,x,y,r){ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r:r*.44;const px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}
function mochiPath(ctx,x,y,r,phase){const w=Math.sin(phase)*.13;ctx.beginPath();ctx.moveTo(x+r*1.15,y);ctx.bezierCurveTo(x+r*.85,y-r*(.82+w),x-r*.45,y-r*(1.05-w),x-r*1.08,y-r*.08);ctx.bezierCurveTo(x-r*.9,y+r*(.82-w),x+r*.42,y+r*(.95+w),x+r*1.15,y);ctx.closePath()}
function drawField(view,sim){const s=sim.snapshot();view.field.parentElement.style.aspectRatio=`${s.config.fieldWidth}/${s.config.fieldHeight}`;const{w,h,dpr}=resizeCanvas(view.field),ctx=view.field.getContext('2d');ctx.clearRect(0,0,w,h);const pad=12*dpr,fw=w-pad*2,fh=h-pad*2,sx=fw/s.config.fieldWidth,sy=fh/s.config.fieldHeight;ctx.fillStyle='#edf6e7';ctx.fillRect(pad,pad,fw,fh);ctx.strokeStyle='#6a7b61';ctx.lineWidth=1.5*dpr;ctx.strokeRect(pad,pad,fw,fh);
 if(s.config.restrictedEnabled){const r={x:s.config.restrictedX,y:s.config.restrictedY,w:s.config.restrictedWidth,h:s.config.restrictedHeight},rx=pad+r.x*sx,ry=pad+r.y*sy,rw=r.w*sx,rh=r.h*sy;ctx.fillStyle='rgba(185,28,28,.18)';if(s.config.restrictedMode==='inside')ctx.fillRect(rx,ry,rw,rh);else{ctx.fillRect(pad,pad,fw,r.y*sy);ctx.fillRect(pad,ry+rh,fw,fh-(r.y+r.h)*sy);ctx.fillRect(pad,ry,r.x*sx,rh);ctx.fillRect(rx+rw,ry,fw-(r.x+r.w)*sx,rh)}ctx.strokeStyle='#b91c1c';ctx.lineWidth=2*dpr;ctx.setLineDash([7*dpr,4*dpr]);ctx.strokeRect(rx,ry,rw,rh);ctx.setLineDash([]);ctx.fillStyle='#991b1b';ctx.font=`bold ${11*dpr}px system-ui`;ctx.fillText(s.config.restrictedMode==='inside'?'内側 立入禁止':'外側 立入禁止',rx+5*dpr,ry+15*dpr)}
 const j=s.jail;ctx.fillStyle='rgba(107,95,80,.12)';ctx.fillRect(pad+j.x*sx,pad+j.y*sy,j.w*sx,j.h*sy);ctx.strokeStyle='#6b5f50';ctx.lineWidth=2*dpr;ctx.setLineDash([5*dpr,4*dpr]);ctx.strokeRect(pad+j.x*sx,pad+j.y*sy,j.w*sx,j.h*sy);ctx.setLineDash([]);ctx.fillStyle='#5b5146';ctx.font=`${11*dpr}px system-ui`;ctx.fillText('ろうや',pad+j.x*sx+5*dpr,pad+j.y*sy+14*dpr);
 if(s.config.symbolRescue){const cx=pad+j.cx*sx,cy=pad+j.cy*sy;ctx.save();ctx.translate(cx,cy);ctx.rotate(s.time*.7);ctx.fillStyle=s.symbol.cooldown>0?'#9ca3af':'#fbbf24';ctx.strokeStyle='#713f12';ctx.lineWidth=1.5*dpr;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?5*dpr:10*dpr;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();if(s.symbol.progress>0){ctx.fillStyle='#1d4ed8';ctx.fillRect(cx-12*dpr,cy+13*dpr,24*dpr*(s.symbol.progress/Math.max(.01,s.config.symbolHold)),3*dpr)}}
 for(const a of s.agents){const x=pad+a.x*sx,y=pad+a.y*sy,r=Math.max(4.5,Math.min(sx,sy)*.32)*dpr*1.5;if(a.team==='oni'){ctx.lineWidth=1.4*dpr;if(a.role==='chaser'){starPath(ctx,x,y,r*1.08);ctx.fillStyle='#ef1717';ctx.strokeStyle='#991b1b';ctx.fill();ctx.stroke()}else if(a.role==='guard'){ctx.beginPath();ctx.rect(x-r*.58,y-r*1.22,r*1.16,r*2.44);ctx.fillStyle='#f97316';ctx.strokeStyle='#9a3412';ctx.fill();ctx.stroke()}else{mochiPath(ctx,x,y,r,s.time*2+a.id);ctx.fillStyle='#d97706';ctx.strokeStyle='#92400e';ctx.fill();ctx.stroke()}}else{ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=a.state==='active'?'#2563eb':a.state==='walkingToJail'?'#9ca3af':'#6b7280';ctx.fill();ctx.strokeStyle=a.protectedUntil>s.time?'#22c55e':'white';ctx.lineWidth=a.protectedUntil>s.time?3*dpr:2*dpr;ctx.stroke();if(a.runnerType!=='standard'){ctx.fillStyle='white';ctx.font=`bold ${7*dpr}px system-ui`;ctx.textAlign='center';ctx.fillText({evader:'逃',oniAvoider:'鬼',rescuer:'助'}[a.runnerType],x,y+2.5*dpr)}}const ringR=r*1.48;if(a.moveMode==='本気で走る'){ctx.strokeStyle='#ef4444';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(x,y,ringR,0,Math.PI*2);ctx.stroke()}else if(a.moveMode==='回復中（歩く）'){ctx.strokeStyle='#64748b';ctx.setLineDash([2*dpr,2*dpr]);ctx.beginPath();ctx.arc(x,y,ringR,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}if(selected?.side===view.side&&selected.id===a.id){ctx.strokeStyle='#111827';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(x,y,r*1.75,0,Math.PI*2);ctx.stroke()}if(a.role==='guard'||a.role==='mochi'){ctx.fillStyle='white';ctx.font=`bold ${8*dpr}px system-ui`;ctx.textAlign='center';ctx.fillText(a.role==='guard'?'守':'餅',x,y+3*dpr)} }
 view.transform={pad,sx,sy,dpr};
}
function drawChart(view,sim){const s=sim.snapshot(),{w,h,dpr}=resizeCanvas(view.chart),ctx=view.chart.getContext('2d');ctx.clearRect(0,0,w,h);const p=8*dpr,max=Math.max(1,s.config.runnerCount);ctx.strokeStyle='#ddd8cc';ctx.beginPath();ctx.moveTo(p,h-p);ctx.lineTo(w-p,h-p);ctx.stroke();ctx.strokeStyle='#f97316';ctx.lineWidth=2*dpr;ctx.beginPath();s.history.forEach((v,i)=>{const x=p+(v.t/s.config.timeLimit)*(w-p*2),y=h-p-(v.n/max)*(h-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#637083';ctx.font=`${10*dpr}px system-ui`;ctx.fillText('つかまった人数',p,12*dpr)}
function renderMetrics(view,sim){const m=sim.metrics();view.metrics.innerHTML=[['つかまった',`${m.caught}人`],['平均待ち',`${m.avgWait.toFixed(1)}秒`],['最長待ち',`${m.maxWait.toFixed(1)}秒`],['救出',`${m.rescues}人`]].map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong></div>`).join('');const headStart=sim.config.oniStartDelay-sim.time;view.status.textContent=sim.finished?sim.result:headStart>0?`逃げが先にスタート／鬼の開始まであと${headStart.toFixed(1)}秒`:`${m.walking}人が牢屋へ歩き、${m.jailed}人が牢屋内、${m.rescues}人が救出`}
function updateSelected(){if(!selected)return;const sim=selected.side==='a'?simA:simB,best=sim.agents.find(a=>a.id===selected.id);if(!best)return;const state=best.team==='oni'?({chaser:'追跡',guard:'守り',mochi:'餅'}[best.role]):`${TYPE_LABELS[best.runnerType]}：${({active:best.action||'活動中',walkingToJail:'牢屋へ歩く',jailed:best.jailMode==='edge'?'境界近くで待つ':'牢屋内を移動'}[best.state])}`;$('#agent-state').textContent=`${state}／${best.moveMode}`}
function renderAll(){updateDiff();views.a.side='a';views.b.side='b';drawField(views.a,simA);drawField(views.b,simB);drawChart(views.a,simA);drawChart(views.b,simB);renderMetrics(views.a,simA);renderMetrics(views.b,simB);updateSelected();els.clock.textContent=formatTime(Math.max(simA.time,simB.time))}
function frame(ts){if(!running)return;if(!last)last=ts;acc+=Math.min(.1,(ts-last)/1000)*Number(els.speed.value);last=ts;let n=0;while(acc>=.05&&n<12){simA.step(.05);simB.step(.05);acc-=.05;n++}playPendingSounds();renderAll();if(simA.finished&&simB.finished){running=false;els.run.textContent='もう一度';els.pause.disabled=true;return}requestAnimationFrame(frame)}
function openSettings(side,trigger){editingSide=side;settingsTrigger=trigger;const config=side==='a'?configA:configB;editingTotal=config.oniCount+config.runnerCount;fillForm(config);els.settings.classList.toggle('left',side==='a');els.sideLabel.textContent=`${side.toUpperCase()}の条件を編集（合計${editingTotal}人）`;els.copyOther.textContent=`${side==='a'?'B':'A'}と同じにする`;els.error.textContent='';els.globalSettings.hidden=true;els.settings.hidden=false;els.scrim.hidden=false;trigger.setAttribute('aria-expanded','true');$('#close-settings').focus()}
function closeSettings(){els.settings.hidden=true;els.globalSettings.hidden=true;els.dualSettings.hidden=true;els.scrim.hidden=true;els.openA.setAttribute('aria-expanded','false');els.openB.setAttribute('aria-expanded','false');if(settingsTrigger){settingsTrigger.setAttribute('aria-expanded','false');settingsTrigger.focus()}settingsTrigger=null}
function updateGlobalComparisonNote(){const selected=COMPARISON_PRESETS[els.globalComparisonPreset.value];els.globalComparisonPresetNote.textContent=selected?selected.note:'現在のA・Bの役割・走力・行動タイプを保ちます。'}
function openGlobalSettings(trigger){settingsTrigger=trigger;const totalA=configA.oniCount+configA.runnerCount,totalB=configB.oniCount+configB.runnerCount;els.globalTotal.value=totalA===totalB?totalA:Math.round((totalA+totalB)/2);els.globalTotalOutput.textContent=els.globalTotal.value;els.globalComparisonPreset.value='keep';updateGlobalComparisonNote();for(const field of GLOBAL_FIELDS){const input=els.globalForm.elements[field],value=configA[field];if(input.type==='checkbox')input.checked=value;else input.value=value}els.globalError.textContent=totalA===totalB?'':`現在はAが${totalA}人、Bが${totalB}人です。反映すると同じ総数になります。`;els.settings.hidden=true;els.dualSettings.hidden=true;els.globalSettings.hidden=false;els.scrim.hidden=false;trigger.setAttribute('aria-expanded','true');$('#close-global-settings').focus()}
function readGlobalForm(){const values={};for(const field of GLOBAL_FIELDS){const input=els.globalForm.elements[field];values[field]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value}return values}
function normalizeTeamForTotal(config,total){const oldTotal=Math.max(1,config.oniCount+config.runnerCount);let oni=Math.round(total*config.oniCount/oldTotal);oni=Math.max(0,total-40,Math.min(15,total-1,oni));const runner=total-oni,next={...config,oniCount:oni,runnerCount:runner};next.guardCount=Math.min(next.guardCount,oni);next.mochiCount=Math.min(next.mochiCount,Math.max(0,oni-next.guardCount));next.captureTarget=Math.min(next.captureTarget,runner);return next}
function applyGlobalSettings(){const total=Math.max(2,Math.min(55,Number(els.globalTotal.value))),shared=readGlobalForm(),comparison=COMPARISON_PRESETS[els.globalComparisonPreset.value],baseA=comparison?PRESETS[comparison.a]:configA,baseB=comparison?PRESETS[comparison.b]:configB,nextA={...normalizeTeamForTotal(baseA,total),...shared},nextB={...normalizeTeamForTotal(baseB,total),...shared},errorsA=validateConfig(nextA),errorsB=validateConfig(nextB);if(errorsA.length||errorsB.length){els.globalError.textContent=[...new Set([...errorsA,...errorsB])].join(' ');return false}configA=nextA;configB=nextB;return true}
function prefixIds(root,prefix){const map=new Map();root.querySelectorAll('[id]').forEach(el=>{map.set(el.id,`${prefix}-${el.id}`);el.id=`${prefix}-${el.id}`});for(const attr of['aria-controls','aria-labelledby','aria-describedby'])root.querySelectorAll(`[${attr}]`).forEach(el=>{const old=el.getAttribute(attr);if(map.has(old))el.setAttribute(attr,map.get(old))})}
function readDualForm(state){const c={...state.config};for(const key of Object.keys(c)){const input=state.form.elements[key];if(!input)continue;if(input.type==='checkbox')c[key]=input.checked;else if(input.type==='number'||input.type==='range')c[key]=Number(input.value);else c[key]=input.value}return c}
function dualSetVisual(state,name,value){state.form.querySelectorAll(`[data-visual-count="${name}"]`).forEach(el=>el.textContent=value)}
function updateDualUI(state){const form=state.form,c=readDualForm(state),types=allocateRunnerTypes(c),oniVariantCount=Math.round(c.oniCount*c.oniVariantPercent/100),runnerVariantCount=Math.round(c.runnerCount*c.runnerVariantPercent/100),used=TYPE_FIELDS.reduce((n,k)=>n+c[k],0);form.querySelectorAll('output[data-for]').forEach(o=>{const n=o.dataset.for,v=Number(form.elements[n].value);o.textContent=n==='rescueTendency'||n.endsWith('Percent')?`${tidyNumber(v)}%`:`${v}（50m ${LEVEL_SECONDS[v-1]}秒相当）`});form.querySelector('[id$="role-equation"]').textContent=`追跡する鬼 ${c.oniCount}−守り${c.guardCount}−餅${c.mochiCount}＝${Math.max(0,c.oniCount-c.guardCount-c.mochiCount)}人`;form.querySelector('[id$="runner-type-equation"]').textContent=`指定 ${tidyNumber(used)}%／標準 ${tidyNumber(100-used)}%`;form.querySelector('[id$="visual-total"]').textContent=c.oniCount+c.runnerCount;dualSetVisual(state,'oniCount',c.oniCount);dualSetVisual(state,'runnerCount',c.runnerCount);dualSetVisual(state,'guardCount',c.guardCount);dualSetVisual(state,'mochiCount',c.mochiCount);dualSetVisual(state,'chaserCount',Math.max(0,c.oniCount-c.guardCount-c.mochiCount));dualSetVisual(state,'oniVariantCount',oniVariantCount);dualSetVisual(state,'runnerVariantCount',runnerVariantCount);for(const field of TYPE_FIELDS)dualSetVisual(state,field.replace('Percent','Count'),types[field]);dualSetVisual(state,'standardCount',types.standard);form.querySelectorAll('[data-restricted]').forEach(el=>el.disabled=!form.elements.restrictedEnabled.checked);form.querySelectorAll('[data-count-adjust]').forEach(button=>{const field=button.dataset.countAdjust,total=field==='oniVariantPercent'?c.oniCount:c.runnerCount,current=field==='oniVariantPercent'?oniVariantCount:runnerVariantCount,delta=Number(button.dataset.delta);button.disabled=delta<0?current<=0:current>=total});form.querySelectorAll('[data-type-adjust]').forEach(button=>{const current=types[button.dataset.typeAdjust],delta=Number(button.dataset.delta);button.disabled=delta<0?current<=0:types.standard<=0})}
function fillDualForm(state,c){state.config={...c};state.total=c.oniCount+c.runnerCount;for(const [key,value]of Object.entries(c)){const input=state.form.elements[key];if(!input)continue;if(input.type==='checkbox')input.checked=value;else input.value=value}state.preset.value=matchPreset(c);state.presetNote.textContent=PRESET_NOTES[state.preset.value];updateDualUI(state)}
function enforceDualLimits(state){const form=state.form,oni=Number(form.elements.oniCount.value),runner=Number(form.elements.runnerCount.value),guard=Math.min(Number(form.elements.guardCount.value),oni);form.elements.guardCount.value=guard;form.elements.mochiCount.value=Math.min(Number(form.elements.mochiCount.value),Math.max(0,oni-guard));form.elements.captureTarget.value=Math.min(Number(form.elements.captureTarget.value),runner)}
function syncDualTotal(state,changed){const form=state.form;if(changed==='oniCount'){const min=Math.max(0,state.total-40),max=Math.min(15,state.total-1),oni=Math.max(min,Math.min(max,Number(form.elements.oniCount.value)));form.elements.oniCount.value=oni;form.elements.runnerCount.value=state.total-oni}else if(changed==='runnerCount'){const min=Math.max(1,state.total-15),max=Math.min(40,state.total),runner=Math.max(min,Math.min(max,Number(form.elements.runnerCount.value)));form.elements.runnerCount.value=runner;form.elements.oniCount.value=state.total-runner}enforceDualLimits(state)}
function dualSetPercent(state,field,count,total){state.form.elements[field].value=total?Math.round(count/total*1000)/10:0}
function adjustDualControl(state,button){const form=state.form,c=readDualForm(state),delta=Number(button.dataset.delta);if(button.dataset.adjust){const field=button.dataset.adjust,input=form.elements[field];let next=Math.max(Number(input.min||0),Math.min(Number(input.max||Infinity),Number(input.value)+delta));if(field==='oniCount'||field==='runnerCount'){input.value=next;syncDualTotal(state,field)}else{if(field==='guardCount')next=Math.min(next,c.oniCount-c.mochiCount);if(field==='mochiCount')next=Math.min(next,c.oniCount-c.guardCount);input.value=Math.max(0,next);enforceDualLimits(state)}}else if(button.dataset.countAdjust){const field=button.dataset.countAdjust,total=field==='oniVariantPercent'?c.oniCount:c.runnerCount,current=Math.round(total*c[field]/100);dualSetPercent(state,field,Math.max(0,Math.min(total,current+delta)),total)}else if(button.dataset.typeAdjust){const field=button.dataset.typeAdjust,counts=allocateRunnerTypes(c);if(delta>0&&counts.standard<=0||delta<0&&counts[field]<=0)return;counts[field]=Math.max(0,counts[field]+delta);for(const typeField of TYPE_FIELDS)dualSetPercent(state,typeField,counts[typeField],c.runnerCount)}state.preset.value='custom';state.presetNote.textContent=PRESET_NOTES.custom;updateDualUI(state)}
function createDualState(side,config){const host=$(`#dual-form-${side}`),form=els.form.cloneNode(true);prefixIds(form,`dual-${side}`);form.removeAttribute('id');form.dataset.side=side;form.querySelector('.settings-actions')?.remove();host.replaceChildren(form);const state={side,form,config:{...config},total:config.oniCount+config.runnerCount,preset:form.querySelector('[id$="preset-select"]'),presetNote:form.querySelector('[id$="preset-note"]')};dualStates[side]=state;fillDualForm(state,config);form.addEventListener('input',e=>{if(e.target===state.preset)return;if(e.target.name==='oniCount'||e.target.name==='runnerCount')syncDualTotal(state,e.target.name);state.preset.value='custom';state.presetNote.textContent=PRESET_NOTES.custom;updateDualUI(state)});state.preset.addEventListener('change',()=>{if(state.preset.value!=='custom')fillDualForm(state,PRESETS[state.preset.value]);else state.presetNote.textContent=PRESET_NOTES.custom});form.addEventListener('click',e=>{const button=e.target.closest('button[data-adjust],button[data-count-adjust],button[data-type-adjust]');if(button)adjustDualControl(state,button)});return state}
function openDualSettings(trigger){settingsTrigger=trigger;createDualState('a',configA);createDualState('b',configB);els.dualError.textContent='';els.settings.hidden=true;els.globalSettings.hidden=true;els.scrim.hidden=true;els.dualSettings.hidden=false;els.openA.setAttribute('aria-expanded','true');els.openB.setAttribute('aria-expanded','true');$('#close-dual-settings').focus()}
function applyDualSettings(){const nextA=readDualForm(dualStates.a),nextB=readDualForm(dualStates.b),errors=[...new Set([...validateConfig(nextA),...validateConfig(nextB)])];if(errors.length){els.dualError.textContent=errors.join(' ');return}configA=nextA;configB=nextB;closeSettings();reset()}
function matchPreset(c){return Object.entries(PRESETS).find(([,preset])=>Object.keys(defaults).every(k=>preset[k]===c[k]))?.[0]??'custom'}
function updatePresetNote(){els.presetNote.textContent=PRESET_NOTES[els.preset.value]}
function fillForm(c){editingTotal=c.oniCount+c.runnerCount;for(const [k,v]of Object.entries(c)){const el=els.form.elements[k];if(!el)continue;if(el.type==='checkbox')el.checked=v;else el.value=v}els.preset.value=matchPreset(c);updatePresetNote();updateRestrictedInputs();updateRangeOutputs();updateEquation();updateRunnerTypeEquation();updateVisualSetup()}
function readForm(){const c={...(editingSide==='a'?configA:configB)};for(const k of Object.keys(c)){const el=els.form.elements[k];if(!el)continue;if(el.type==='checkbox')c[k]=el.checked;else if(el.type==='number'||el.type==='range')c[k]=Number(el.value);else c[k]=el.value}return c}
function tidyNumber(v){return Number.isInteger(v)?String(v):v.toFixed(1)}
function updateRangeOutputs(){els.form.querySelectorAll('output[data-for]').forEach(o=>{const n=o.dataset.for,v=Number(els.form.elements[n].value);o.textContent=n==='rescueTendency'||n.endsWith('Percent')?`${tidyNumber(v)}%`:`${v}（50m ${LEVEL_SECONDS[v-1]}秒相当）`})}
function updateEquation(){const c=readForm();$('#role-equation').textContent=`追跡する鬼 ${c.oniCount}−守り${c.guardCount}−餅${c.mochiCount}＝${c.oniCount-c.guardCount-c.mochiCount}人`}
function updateRunnerTypeEquation(){const c=readForm(),used=TYPE_FIELDS.reduce((n,k)=>n+c[k],0);$('#runner-type-equation').textContent=`指定 ${tidyNumber(used)}%／標準 ${tidyNumber(100-used)}%`}
function allocateRunnerTypes(c){const groups=TYPE_FIELDS.map((field,index)=>({field,index,raw:c.runnerCount*c[field]/100})),used=TYPE_FIELDS.reduce((n,k)=>n+c[k],0);groups.push({field:'standard',index:groups.length,raw:c.runnerCount*(100-used)/100});for(const g of groups){g.count=Math.floor(Math.max(0,g.raw));g.fraction=g.raw-g.count}let remaining=c.runnerCount-groups.reduce((n,g)=>n+g.count,0);const ranked=[...groups].sort((a,b)=>b.fraction-a.fraction||a.index-b.index);for(let i=0;i<remaining;i++)ranked[i%ranked.length].count++;return Object.fromEntries(groups.map(g=>[g.field,g.count]))}
function setVisualValue(name,value){els.form.querySelectorAll(`[data-visual-count="${name}"]`).forEach(el=>el.textContent=value)}
function updateVisualSetup(){const c=readForm(),types=allocateRunnerTypes(c),oniVariantCount=Math.round(c.oniCount*c.oniVariantPercent/100),runnerVariantCount=Math.round(c.runnerCount*c.runnerVariantPercent/100);$('#visual-total').textContent=c.oniCount+c.runnerCount;setVisualValue('oniCount',c.oniCount);setVisualValue('runnerCount',c.runnerCount);setVisualValue('guardCount',c.guardCount);setVisualValue('mochiCount',c.mochiCount);setVisualValue('chaserCount',Math.max(0,c.oniCount-c.guardCount-c.mochiCount));setVisualValue('oniVariantCount',oniVariantCount);setVisualValue('runnerVariantCount',runnerVariantCount);for(const field of TYPE_FIELDS)setVisualValue(field.replace('Percent','Count'),types[field]);setVisualValue('standardCount',types.standard);els.form.querySelectorAll('[data-count-adjust]').forEach(button=>{const field=button.dataset.countAdjust,total=field==='oniVariantPercent'?c.oniCount:c.runnerCount,current=field==='oniVariantPercent'?oniVariantCount:runnerVariantCount,delta=Number(button.dataset.delta);button.disabled=delta<0?current<=0:current>=total});els.form.querySelectorAll('[data-type-adjust]').forEach(button=>{const field=button.dataset.typeAdjust,current=types[field],delta=Number(button.dataset.delta);button.disabled=delta<0?current<=0:types.standard<=0})}
function setPercentFromCount(field,count,total){els.form.elements[field].value=total?Math.round(count/total*1000)/10:0}
function enforceFormRoleLimits(){const oni=Number(els.form.elements.oniCount.value),runner=Number(els.form.elements.runnerCount.value),guard=Math.min(Number(els.form.elements.guardCount.value),oni);els.form.elements.guardCount.value=guard;els.form.elements.mochiCount.value=Math.min(Number(els.form.elements.mochiCount.value),Math.max(0,oni-guard));els.form.elements.captureTarget.value=Math.min(Number(els.form.elements.captureTarget.value),runner)}
function syncTeamTotal(changedField){if(changedField==='oniCount'){const minOni=Math.max(0,editingTotal-40),maxOni=Math.min(15,editingTotal-1),oni=Math.max(minOni,Math.min(maxOni,Number(els.form.elements.oniCount.value)));els.form.elements.oniCount.value=oni;els.form.elements.runnerCount.value=editingTotal-oni}else if(changedField==='runnerCount'){const minRunner=Math.max(1,editingTotal-15),maxRunner=Math.min(40,editingTotal),runner=Math.max(minRunner,Math.min(maxRunner,Number(els.form.elements.runnerCount.value)));els.form.elements.runnerCount.value=runner;els.form.elements.oniCount.value=editingTotal-runner}enforceFormRoleLimits()}
function adjustVisualNumber(field,delta){const input=els.form.elements[field],c=readForm(),min=Number(input.min||0),max=Number(input.max||Infinity);let next=Math.max(min,Math.min(max,Number(input.value)+delta));if(field==='oniCount'||field==='runnerCount'){input.value=next;syncTeamTotal(field);return}if(field==='guardCount')next=Math.min(next,c.oniCount-c.mochiCount);if(field==='mochiCount')next=Math.min(next,c.oniCount-c.guardCount);input.value=Math.max(0,next);enforceFormRoleLimits()}
function adjustVisualCount(field,delta){const c=readForm(),total=field==='oniVariantPercent'?c.oniCount:c.runnerCount,current=Math.round(total*c[field]/100);setPercentFromCount(field,Math.max(0,Math.min(total,current+delta)),total)}
function adjustVisualType(field,delta){const c=readForm(),counts=allocateRunnerTypes(c),next=Math.max(0,counts[field]+delta);if(delta>0&&counts.standard<=0||delta<0&&counts[field]<=0)return;counts[field]=next;for(const typeField of TYPE_FIELDS)setPercentFromCount(typeField,counts[typeField],c.runnerCount)}
function refreshSettingsAfterVisualChange(){els.preset.value='custom';updatePresetNote();updateRangeOutputs();updateEquation();updateRunnerTypeEquation();updateVisualSetup()}
function updateRestrictedInputs(){const enabled=els.form.elements.restrictedEnabled.checked;els.form.querySelectorAll('[data-restricted]').forEach(el=>el.disabled=!enabled)}
function selectFromCanvas(side,e){const view=views[side],sim=side==='a'?simA:simB,t=view.transform,r=view.field.getBoundingClientRect(),x=(e.clientX-r.left)*(view.field.width/r.width),y=(e.clientY-r.top)*(view.field.height/r.height);let best=null,bd=Infinity;for(const a of sim.agents){const px=t.pad+a.x*t.sx,py=t.pad+a.y*t.sy,d=Math.hypot(x-px,y-py);if(d<bd){bd=d;best=a}}if(!best||bd>24*t.dpr)return;selected={side,id:best.id};els.selected.hidden=false;$('#agent-name').textContent=`${side.toUpperCase()}：${best.team==='oni'?'鬼':'逃げ'} ${best.id}`;$('#agent-state').textContent=best.team==='oni'?({chaser:'追跡',guard:'守り',mochi:'餅'}[best.role]):({active:best.action||'活動中',jailed:'牢屋で待機'}[best.state]);$('#agent-level').value=best.level;$('#agent-level-output').textContent=`${best.level}（50m ${LEVEL_SECONDS[best.level-1]}秒相当）`;renderAll()}

els.run.addEventListener('click',()=>{ensureAudio();if(simA.finished&&simB.finished)reset();running=true;els.run.textContent='実験中';els.pause.disabled=false;last=0;requestAnimationFrame(frame)});els.pause.addEventListener('click',()=>{running=!running;els.pause.textContent=running?'一時停止':'再開';if(running){ensureAudio();last=0;requestAnimationFrame(frame)}});els.reset.addEventListener('click',reset);els.newSeed.addEventListener('click',()=>{seed=(seed+7919)>>>0;reset()});els.openGlobal.addEventListener('click',()=>openGlobalSettings(els.openGlobal));els.openA.addEventListener('click',()=>openDualSettings(els.openA));els.openB.addEventListener('click',()=>openDualSettings(els.openB));$('#close-settings').addEventListener('click',closeSettings);$('#close-global-settings').addEventListener('click',closeSettings);$('#close-dual-settings').addEventListener('click',closeSettings);$('#apply-dual-settings').addEventListener('click',applyDualSettings);$('#copy-a-to-b').addEventListener('click',()=>fillDualForm(dualStates.b,readDualForm(dualStates.a)));$('#copy-b-to-a').addEventListener('click',()=>fillDualForm(dualStates.a,readDualForm(dualStates.b)));els.scrim.addEventListener('click',closeSettings);els.copyOther.addEventListener('click',()=>fillForm(editingSide==='a'?configB:configA));els.form.addEventListener('input',e=>{if(e.target.name==='oniCount'||e.target.name==='runnerCount')syncTeamTotal(e.target.name);updateRangeOutputs();updateEquation();updateRunnerTypeEquation();updateVisualSetup()});els.form.addEventListener('click',e=>{const button=e.target.closest('button[data-adjust],button[data-count-adjust],button[data-type-adjust]');if(!button)return;if(button.dataset.adjust)adjustVisualNumber(button.dataset.adjust,Number(button.dataset.delta));if(button.dataset.countAdjust)adjustVisualCount(button.dataset.countAdjust,Number(button.dataset.delta));if(button.dataset.typeAdjust)adjustVisualType(button.dataset.typeAdjust,Number(button.dataset.delta));refreshSettingsAfterVisualChange()});els.form.addEventListener('submit',e=>{e.preventDefault();const next=readForm(),errors=validateConfig(next);els.error.textContent=errors.join(' ');if(errors.length)return;if(editingSide==='a')configA=next;else configB=next;closeSettings();reset()});els.globalForm.addEventListener('submit',e=>{e.preventDefault();if(!applyGlobalSettings())return;closeSettings();reset()});
for(const side of['a','b'])views[side].field.addEventListener('click',e=>selectFromCanvas(side,e));$('#agent-level').addEventListener('input',e=>{if(!selected)return;const sim=selected.side==='a'?simA:simB;sim.setAgentLevel(selected.id,e.target.value);$('#agent-level-output').textContent=`${e.target.value}（50m ${LEVEL_SECONDS[e.target.value-1]}秒相当）`;renderAll()});window.addEventListener('resize',renderAll);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(!els.settings.hidden||!els.globalSettings.hidden||!els.dualSettings.hidden))closeSettings()});
els.layout.addEventListener('change',()=>{document.querySelector('.comparison').classList.toggle('stacked',els.layout.value==='stacked');requestAnimationFrame(renderAll)});
els.form.elements.restrictedEnabled.addEventListener('change',updateRestrictedInputs);
els.preset.addEventListener('change',()=>{if(els.preset.value!=='custom')fillForm(PRESETS[els.preset.value]);else updatePresetNote()});
els.form.addEventListener('input',e=>{if(e.target!==els.preset){els.preset.value='custom';updatePresetNote()}});
els.globalTotal.addEventListener('input',()=>{const value=Math.max(2,Math.min(55,Number(els.globalTotal.value)||2));els.globalTotal.value=value;els.globalTotalOutput.textContent=value});
els.globalComparisonPreset.addEventListener('change',updateGlobalComparisonNote);
$('#global-total-minus').addEventListener('click',()=>{els.globalTotal.value=Math.max(2,Number(els.globalTotal.value)-1);els.globalTotalOutput.textContent=els.globalTotal.value});
$('#global-total-plus').addEventListener('click',()=>{els.globalTotal.value=Math.min(55,Number(els.globalTotal.value)+1);els.globalTotalOutput.textContent=els.globalTotal.value});
reset();
