import test from'node:test';import assert from'node:assert/strict';import{Simulation,defaults,levelSpeed,validateConfig}from'../simulator.js';
test('同じ条件と種なら同じ結果になる',()=>{const a=new Simulation(defaults,42),b=new Simulation(defaults,42);for(let i=0;i<1000;i++){a.step();b.step()}assert.deepEqual(a.history,b.history);assert.deepEqual(a.metrics(),b.metrics())});
test('走力レベルが上がるほど速度が上がる',()=>{for(let i=1;i<10;i++)assert.ok(levelSpeed(i)<levelSpeed(i+1))});
test('守りと餅は鬼の総数を超えない',()=>{assert.ok(validateConfig({...defaults,oniCount:2,guardCount:2,mochiCount:1}).length>0)});
test('捕獲目標は逃げ人数以下',()=>{assert.ok(validateConfig({...defaults,runnerCount:3,captureTarget:4}).length>0)});
test('追跡0人も有効な条件',()=>{assert.equal(validateConfig({...defaults,oniCount:3,guardCount:2,mochiCount:1,captureTarget:10}).length,0)});
test('餅が担当する逃げはタッチされても残る',()=>{const sim=new Simulation({...defaults,oniCount:1,guardCount:0,mochiCount:1,runnerCount:2,captureTarget:2,mochiLimit:30},7);const oni=sim.agents[0],runners=sim.agents.filter(a=>a.team==='runner');sim.capture(runners[0],oni);sim.arriveJail(runners[0]);sim.assignMochi();assert.equal(runners[0].mochiBy,oni.id);assert.equal(sim.rescue(runners[0],runners[1]),false);assert.equal(runners[0].state,'jailed')});
test('餅の時間は再捕獲時にリセットされる',()=>{const sim=new Simulation({...defaults,oniCount:1,guardCount:0,mochiCount:1,runnerCount:2,captureTarget:2,mochiLimit:1},9);const oni=sim.agents[0],runners=sim.agents.filter(a=>a.team==='runner'),r=runners[0];sim.capture(r,oni);sim.arriveJail(r);sim.assignMochi();r.mochiElapsed=1;sim.releaseMochi(r);sim.rescue(r,runners[1]);sim.capture(r,oni);assert.equal(r.mochiElapsed,0)});
test('捕まった逃げは歩いてから牢屋状態になる',()=>{const sim=new Simulation({...defaults,oniCount:1,runnerCount:1,captureTarget:1},3),oni=sim.agents[0],r=sim.agents[1];r.x=sim.jail.cx+1;r.y=sim.jail.cy;sim.capture(r,oni);assert.equal(r.state,'walkingToJail');for(let i=0;i<30;i++)sim.move(r,.05);assert.equal(r.state,'jailed');assert.ok(r.jailedAt!==null)});
test('本気の時間を使うと回復歩きに入る',()=>{const sim=new Simulation({...defaults,sprintDuration:.1,recoveryDuration:20},4),a=sim.agents.find(x=>x.role==='chaser');a.wantsSprint=true;a.vx=1;a.vy=0;sim.move(a,.05);sim.time+=.05;sim.move(a,.05);assert.ok(a.recoveryUntil>=20);sim.time+=.05;sim.move(a,.05);assert.equal(a.moveMode,'回復中（歩く）')});
test('牢屋内で本人に触れたときだけ解放される',()=>{const sim=new Simulation({...defaults,oniCount:1,runnerCount:2,mochiCount:0},6),oni=sim.agents[0],runners=sim.agents.filter(a=>a.team==='runner');sim.capture(runners[0],oni);assert.equal(sim.rescue(runners[0],runners[1]),false);sim.arriveJail(runners[0]);assert.equal(sim.rescue(runners[0],runners[1]),true);assert.equal(runners[0].state,'active')});

